### ISSUE TITLE
Can't compile on Windows with MinGW! Too many errors, can't configure!

### ISSUE THREAD

**Issue by saifali96** [orangeduck/Corange#18]
Hi @orangeduck :)
It's been a few days since I'm trying to get this to work, I use elementaryOS in VMWare Workstation, I installed SDL libs and compiled it compiles clean, now I seriously don't know if it creates an executable or what, though I tried executing the compiled files, no luck though. I now know it compiles to a library(much like a dll on Windows).
Anyway metaballs didn't compile. Rest compile but don't run(execute but don't render) except for Platformer(cool game) and sea(really bad graphics don't know why). I think it's because of virtual machine, that's why it can't use my GPU to render out things properly?

That's why I returned to Windows 10, installed SDL dev libraries for Visual Studio(my main IDE), tried my best, couldn't get it to work. Tried other things with SDL, they worked like a charm, Corange didn't. 

Next came MinGW, installed dev libraries, linked them. tonnes of errors(redefinitions and what not in SDL_Local.h, SDL_Local.c and SDL_opengl), fixed an error by commenting a block of code, worked and it compiled almost every src to obj except it stuck somewhere in the end, now can't fix that one. Fiddled, but no luck.

**Can you please help me?**
Do you happen to have a Visual Studio project of Corange? Are you able to run it MinGW?
If yes! help to do so too!

PS: I recently completed your book! It was an excellent source of learning C, please do check my repositories for my Lispi, well wait here's the link [Lispi](https://github.com/saifali96/Lispi).
**Thanks**

**Comment by orangeduck** [comment]
Hi,

It sounds like you essentially compiled it correctly in the VM but that your graphics card is not good enough to run the demos. You can check the log files which are created when you run the program to find out specifically what the errors are.

Perhaps you can tell me the specific errors you had either with Corange in Visual Studio or with using MinGW so I can help you?

Sorry it has been a while since I supported this project so it is often hard to ensure it is always easy to compile.

I'm glad you liked the book! Congrats on completing it.

- Dan
